### ISSUE TITLE
Remove MPU6050 from master branch

### ISSUE THREAD

**Issue by J0hnCena** [Impact2585/Lib2585#54]
Since the MPU6050 is not able to connect to the roboRIO through I2C, the MPU6050 should be removed from the master branch. However, there is a possibility of it working if we try to connect by brute forcing every single possible address, so it should be kept on the MPU6050-dev branch.

**Comment by LoadingPleaseWait** [comment]
@J0hnCena, do you actually want me to do this issue? I will definitely do this if you want me to but I just want to make sure that you didn't assign me by accident.

**Comment by J0hnCena** [comment]
Yeah, I can't bring myself to delete MPU6050.

**Comment by LoadingPleaseWait** [comment]
Alright, I'll do it right now.

**Comment by LoadingPleaseWait** [comment]
I realized that this has broken reverse compatibility between master and Lib2585 v2.3.1. Lib2585 has broken reverse compatibility before and is not used by any other teams, as far as I know. This should still be noted though.
